In [49]:
#dependencies
import pandas as pd
import requests
from sqlalchemy import create_engine
from flask import Flask,jsonify,render_template,Response
import json
import pickle

In [18]:
# DSCI data
dsci_path = "us_dsci_data.csv"
dsci_df = pd.read_csv(dsci_path)
dsci_df = dsci_df.rename(columns={"Name": "state", "MapDate": "date", "DSCI":"dsci"})

dsci_df

         state      date  dsci
0      Alabama  20141230    41
1      Alabama  20150106    21
2      Alabama  20150113    21
3      Alabama  20150120    46
4      Alabama  20150127    41
...        ...       ...   ...
17095  Wyoming  20210615   203
17096  Wyoming  20210622   227
17097  Wyoming  20210629   244
17098  Wyoming  20210706   246
17099  Wyoming  20210713   253

[17100 rows x 3 columns]

In [19]:
engine = create_engine('postgresql://postgres:postgres@localhost/project_2')
engine.connect()

In [129]:
print(engine)

Engine(postgresql://postgres:***@localhost/project_2)

In [20]:
dsci_df.to_sql(name="drought_severity",con=engine, if_exists="append")

IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "drought_severity_pkey"
DETAIL:  Key (index)=(0) already exists.

[SQL: INSERT INTO drought_severity (index, state, date, dsci) VALUES (%(index)s, %(state)s, %(date)s, %(dsci)s)]
[parameters: ({'index': 0, 'state': 'Alabama', 'date': 20141230, 'dsci': 41}, {'index': 1, 'state': 'Alabama', 'date': 20150106, 'dsci': 21}, {'index': 2, 'state': 'Alabama', 'date': 20150113, 'dsci': 21}, {'index': 3, 'state': 'Alabama', 'date': 20150120, 'dsci': 46}, {'index': 4, 'state': 'Alabama', 'date': 20150127, 'dsci': 41}, {'index': 5, 'state': 'Alabama', 'date': 20150203, 'dsci': 41}, {'index': 6, 'state': 'Alabama', 'date': 20150210, 'dsci': 64}, {'index': 7, 'state': 'Alabama', 'date': 20150217, 'dsci': 86}  ... displaying 10 of 17100 total bound parameter sets ...  {'index': 17098, 'state': 'Wyoming', 'date': 20210706, 'dsci': 246}, {'index': 17099, 'state': 'Wyoming', 'date': 20210713, 'dsci': 253})]
(Background on this error at: http://sqlalche.me/e/13/gkpj)

CA Drought by County since 2015

In [23]:
ca_county = "ca_drought_data.csv"
ca_county_df = pd.read_csv(ca_county)
ca_county_df = ca_county_df.rename(columns={"FIPS": "fips", "StartDate": "start_date", "EndDate":"end_date", "ConsecutiveWeeks":"consecutiveweeks",
                                           "State":"state", "County":"county"})
ca_county_df.head(50)

    fips  start_date    end_date  consecutiveweeks state               county
0   6001  2015-12-31  2017-02-09                58    CA       Alameda County
1   6001  2018-02-22  2019-02-07                50    CA       Alameda County
2   6001  2019-11-14  2019-12-05                 3    CA       Alameda County
3   6001  2020-01-30  2021-07-01                75    CA       Alameda County
4   6003  2015-12-31  2017-01-19                55    CA        Alpine County
5   6003  2018-02-01  2018-04-05                10    CA        Alpine County
6   6003  2018-06-28  2019-01-24                30    CA        Alpine County
7   6003  2019-10-17  2019-12-05                 7    CA        Alpine County
8   6003  2020-01-30  2021-07-01                75    CA        Alpine County
9   6005  2015-12-31  2017-02-09                58    CA        Amador County
10  6005  2018-02-01  2018-03-22                 8    CA        Amador County
11  6005  2018-06-28  2019-01-24                30    CA        Amador County
12  6005  2019-10-24  2019-12-05                 6    CA        Amador County
13  6005  2020-01-30  2021-07-01                75    CA        Amador County
14  6007  2015-12-31  2017-01-05                53    CA         Butte County
15  6007  2018-02-08  2019-01-31                51    CA         Butte County
16  6007  2019-11-14  2019-12-05                 3    CA         Butte County
17  6007  2020-01-30  2021-07-01                75    CA         Butte County
18  6009  2015-12-31  2017-02-23                60    CA     Calaveras County
19  6009  2018-02-01  2018-04-05                10    CA     Calaveras County
20  6009  2018-06-28  2019-01-24                30    CA     Calaveras County
21  6009  2019-10-24  2019-12-05                 6    CA     Calaveras County
22  6009  2020-01-30  2021-07-01                75    CA     Calaveras County
23  6011  2015-12-31  2017-01-05                53    CA        Colusa County
24  6011  2018-02-08  2019-02-07                52    CA        Colusa County
25  6011  2019-11-14  2019-12-05                 3    CA        Colusa County
26  6011  2020-01-30  2021-07-01                75    CA        Colusa County
27  6013  2015-12-31  2017-02-09                58    CA  Contra Costa County
28  6013  2018-02-22  2019-01-24                48    CA  Contra Costa County
29  6013  2019-11-14  2019-12-05                 3    CA  Contra Costa County
30  6013  2020-01-30  2021-07-01                75    CA  Contra Costa County
31  6015  2015-12-31  2016-03-24                13    CA     Del Norte County
32  6015  2016-06-09  2016-10-13                19    CA     Del Norte County
33  6015  2018-06-07  2019-02-28                38    CA     Del Norte County
34  6015  2020-02-27  2021-07-01                71    CA     Del Norte County
35  6017  2015-12-31  2017-01-19                55    CA     El Dorado County
36  6017  2018-02-01  2018-03-22                 8    CA     El Dorado County
37  6017  2018-06-28  2019-01-24                30    CA     El Dorado County
38  6017  2019-10-24  2019-12-05                 6    CA     El Dorado County
39  6017  2020-01-30  2021-07-01                75    CA     El Dorado County
40  6019  2015-12-31  2019-02-14               161    CA        Fresno County
41  6019  2016-11-23  2018-11-21                 3    CA        Fresno County
42  6019  2019-10-17  2019-12-05                 7    CA        Fresno County
43  6019  2020-01-30  2021-07-01                75    CA        Fresno County
44  6021  2015-12-31  2017-01-05                53    CA         Glenn County
45  6021  2018-02-08  2019-02-14                53    CA         Glenn County
46  6021  2019-11-14  2019-12-05                 3    CA         Glenn County
47  6021  2020-01-30  2021-07-01                75    CA         Glenn County
48  6023  2015-12-31  2016-10-13                42    CA      Humboldt County
49  6023  2018-01-11  2018-02-01                 4    CA      Humboldt County

In [65]:
ca_county_df.to_sql(name="ca_drought",con=engine, if_exists="append")

In [131]:
test = engine.execute("SELECT index, fips, start_date, end_date, consecutiveweeks, state, county FROM ca_drought WHERE end_date = '2021-07-01' ORDER BY county;").fetchall()

In [79]:
with open('US_Counties.json', 'r') as f:  
    data = json.loads(f.read())

df_nested_list = pd.json_normalize(data, record_path=['features'])
df_nested_list.head()

,type,properties.GEO_ID,properties.STATE,properties.COUNTY,properties.NAME,properties.LSAD,properties.CENSUSAREA,geometry.type,geometry.coordinates
0,Feature,0500000US01029,01,029,Cleburne,County,560.100,Polygon,"[[[-85.388717, 33.913044], [-85.380885, 33.873..."
1,Feature,0500000US01031,01,031,Coffee,County,678.972,Polygon,"[[[-86.030441, 31.618939], [-86.004085, 31.619..."
2,Feature,0500000US01037,01,037,Coosa,County,650.926,Polygon,"[[[-86.00928, 33.101638], [-86.00917, 33.09026..."
3,Feature,0500000US01039,01,039,Covington,County,1030.456,Polygon,"[[[-86.348506, 30.994339], [-86.35023, 30.9943..."
4,Feature,0500000US01041,01,041,Crenshaw,County,608.840,Polygon,"[[[-86.146992, 31.680455], [-86.147114, 31.663..."

In [90]:
county_coord = df_nested_list.loc[:,["properties.STATE", "properties.NAME", "properties.LSAD", "geometry.coordinates"]]
county_coord = county_coord.rename(columns = {"properties.STATE":"state_id", "properties.NAME":"name", "properties.LSAD":"lsad", 
                                   "geometry.coordinates":"coordinates"})
county_coord["county"] = county_coord["name"].astype(str) + ' ' + county_coord["lsad"]
county_coord = county_coord.drop(["name", "lsad"], axis=1)
county_coord = county_coord.loc[county_coord["state_id"] == "06"]
county_coord["state_id"] = county_coord["state_id"].astype("int")
county_coord["coordinates"] = county_coord["coordinates"].astype('string')
county_coord["county"] = county_coord["county"].astype('string')
county_coord.dtypes
# bxcounty_coord = pickle.dumps(county_coord["coordinates"])
# pickle.loads(bxcounty_coord)

# county_coord["coordinates"] = pickle.dumps(county_coord["coordinates"])
# county_coord.head()

state_id        int32
coordinates    string
county         string
dtype: object

In [75]:
county_coord.to_sql(name="ca_coord",con=engine, if_exists="append", index=False)

DataError: (psycopg2.errors.ArraySubscriptError) multidimensional arrays must have array expressions with matching dimensions

[SQL: INSERT INTO ca_coord (state_id, coordinates, county) VALUES (%(state_id)s, %(coordinates)s, %(county)s)]
[parameters: ({'state_id': '06', 'coordinates': [[[-119.998671, 40.779521], [-119.998479, 40.749899], [-119.997533, 40.720992], [-119.995926, 40.499901], [-119.996051, 40.402326], [-119.996155, 40.3 ... (4885 characters truncated) ... 999866, 41.183974], [-119.999585, 41.011915], [-119.999358, 40.873101], [-119.999232, 40.867454], [-119.999231, 40.865899], [-119.998671, 40.779521]]], 'county': 'Lassen County'}, {'state_id': '06', 'coordinates': [[[-120.488222, 41.993736], [-120.328587, 41.993132], [-120.326005, 41.993122], [-120.286424, 41.993058], [-120.272209, 41.993265], [-120.181563, 41.9 ... (1874 characters truncated) ... 693941, 41.993676], [-120.692219, 41.993677], [-120.647173, 41.993084], [-120.624304, 41.993194], [-120.501069, 41.993785], [-120.488222, 41.993736]]], 'county': 'Modoc County'}, {'state_id': '06', 'coordinates': [[[[-123.013916, 37.700355], [-123.013897, 37.704478], [-123.012194, 37.706749], [-123.004489, 37.706262], [-123.00019, 37.702937], [-122.997189, 37.6 ... (3877 characters truncated) ... 486042, 37.708233], [-122.502427, 37.708133], [-122.506483, 37.723731], [-122.50784, 37.735428], [-122.509397, 37.748841], [-122.511137, 37.763838]]]], 'county': 'San Francisco County'}, {'state_id': '06', 'coordinates': [[[[-119.789798, 34.05726], [-119.770729, 34.055051], [-119.766081, 34.05537], [-119.763688, 34.057155], [-119.755521, 34.056716], [-119.739472, 34.04 ... (27257 characters truncated) ... .453547, 34.39607], [-119.453994, 34.39569], [-119.454101, 34.395568], [-119.458481, 34.393367], [-119.459396, 34.391963], [-119.463214, 34.390549]]]], 'county': 'Santa Barbara County'}, {'state_id': '06', 'coordinates': [[[-120.003117, 39.445044], [-120.074157, 39.445119], [-120.075669, 39.445196], [-120.096007, 39.445098], [-120.120216, 39.445132], [-120.126009, 39.4 ... (11646 characters truncated) ... .001652, 39.577355], [-120.00174, 39.538852], [-120.001771, 39.536772], [-120.002363, 39.496397], [-120.003116, 39.445113], [-120.003117, 39.445044]]], 'county': 'Sierra County'}, {'state_id': '06', 'coordinates': [[[-122.266669, 38.06007], [-122.273006, 38.07438], [-122.282824, 38.082889], [-122.301804, 38.105142], [-122.302075, 38.105357], [-122.313393, 38.114 ... (12337 characters truncated) ... 22.227991, 38.061206], [-122.232079, 38.06182], [-122.234733, 38.06237], [-122.245483, 38.063922], [-122.263451, 38.060302], [-122.266669, 38.06007]]], 'county': 'Solano County'}, {'state_id': '06', 'coordinates': [[[-121.414714, 38.979429], [-121.414413, 38.94085], [-121.414399, 38.926214], [-121.451782, 38.92609], [-121.469356, 38.925992], [-121.46947, 38.8969 ... (13866 characters truncated) ... 437527, 38.993628], [-121.422068, 38.996332], [-121.417517, 38.995962], [-121.414885, 38.996429], [-121.414652, 38.995305], [-121.414714, 38.979429]]], 'county': 'Sutter County'}, {'state_id': '06', 'coordinates': [[[-123.332193, 39.977305], [-123.33258, 39.977304], [-123.341029, 39.977291], [-123.447329, 39.977196], [-123.544563, 39.977015], [-123.544458, 40.00 ... (33359 characters truncated) ... 934984, 39.986189], [-122.935599, 39.984125], [-122.937083, 39.981867], [-122.934608, 39.980138], [-122.934013, 39.978131], [-123.332193, 39.977305]]], 'county': 'Trinity County'}  ... displaying 10 of 58 total bound parameter sets ...  {'state_id': '06', 'coordinates': [[[-119.547406, 38.143977], [-119.545551, 38.143072], [-119.541889, 38.144653], [-119.538085, 38.144097], [-119.531162, 38.144486], [-119.526711, 38.1 ... (30780 characters truncated) ... .548343, 38.154616], [-119.546947, 38.15442], [-119.545501, 38.153056], [-119.545573, 38.151486], [-119.547952, 38.148115], [-119.547406, 38.143977]]], 'county': 'Tuolumne County'}, {'state_id': '06', 'coordinates': [[[-121.95312, 38.525636], [-121.960398, 38.523008], [-121.963606, 38.522802], [-121.967629, 38.520205], [-121.967836, 38.520098], [-121.970688, 38.51 ... (15486 characters truncated) ... .941547, 38.533068], [-121.942422, 38.532466], [-121.944623, 38.528933], [-121.947456, 38.527096], [-121.948482, 38.526767], [-121.95312, 38.525636]]], 'county': 'Yolo County'})]
(Background on this error at: http://sqlalche.me/e/13/9h9h)